### ISSUE TITLE
BAF correction above 0.6

### ISSUE THREAD

**Issue by jgarces02** [hanasusak/cDriver#1]
Dear @hanasusak, 

Thanks for your CCF calculation method, I found it very easy to use (and very applicable)! If you don't mind, I've a question related with BAF correction: why in values above 0.6 `ccfPlody` is again calculated (moreover, taking account a ploidy of 1 and not 2) instead of _saturate_ final CCF values to 1 like in correction of BAFs between 0.5 and 0.6?

Thanks for your help. Regards.

**Comment by hanasusak** [comment]
Hi @jgarces02, 

CCF (cancer cell fraction) as a concept can take values [0,1], but it happens from time to time that using VAF/BAF as described CCF fraction is estimated to be above 1. There are two most common reasons for this i) VAF value is estimated itself, therefore, when the true value is 0.5 (max in the diploid region) from reads can be estimated to close by value  (especially if there is low coverage). Further, I would not expect that estimates go above 0.6 if the true value is 0.5  (this is just arbitrary value, but in reality should be estimated using read depth); ii) If CCF is estimated to be above 1.2 (VAF >0.6) then possible reason for this  is that deletion is missed and true ploidy is 1. Moreover, if VAF values are very high (close to 1) and it is heterozygote somatic mutation,  then deletion is an only reasonable explanation to my knowledge ( loss of heterozygosity (loh) ).  
I hope this clears some of my thinking when coding CCF estimation. And sorry for the late reply.

**Comment by jgarces02** [comment]
Ok, I think it's more clear... Thanks a lot!
